version: "3.7"

services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8000:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: develop
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgres/data
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:var/lib/postgressql/data
volumes:
  postgres-data:
  pgadmin-data:
